[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  included_files = ["**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self'; script-src 'self' https://platform.twitter.com; frame-src 'self' https://syndication.twitter.com/ https://platform.twitter.com/;"
