[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  included_files = ["**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' https://platform.twitter.com; style-src 'self' 'unsafe-inline' https://platform.twitter.com; frame-src 'self' https://syndication.twitter.com/ https://platform.twitter.com/; img-src 'self' https://pbs.twimg.com data:; connect-src 'self' https://syndication.twitter.com https://api.twitter.com;"