[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  included_files = ["**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://platform.twitter.com https://unpkg.com https://www.googletagmanager.com https://udify.app; style-src 'self' 'unsafe-inline' https://platform.twitter.com https://fonts.googleapis.com https://unpkg.com; font-src 'self' https://fonts.gstatic.com; frame-src 'self' https://syndication.twitter.com/ https://platform.twitter.com/ https://udify.app; img-src 'self' https://pbs.twimg.com https://www.google-analytics.com https://udify.app data:; connect-src 'self' https://syndication.twitter.com https://api.twitter.com https://www.google-analytics.com https://region1.google-analytics.com https://udify.app;"